# Generated by Django 4.2.9 on 2024-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Start Time')),
            ],
        ),
    ]
