# Generated by Django 4.2.9 on 2024-02-06 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Member Name')),
                ('memberNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('classLevel', models.CharField(max_length=10, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Show Name')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.member')),
            ],
        ),
        migrations.CreateModel(
            name='EBoard',
            fields=[
                ('position', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Postion')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.member')),
            ],
        ),
    ]
